ViridianSchoolHouse_Script:
	jp EnableAutoTextBoxDrawing

ViridianSchoolHouse_TextPointers:
	def_text_pointers
	dw_const ViridianSchoolHouseBrunetteGirlText, TEXT_VIRIDIANSCHOOLHOUSE_BRUNETTE_GIRL
	dw_const ViridianSchoolHouseCooltrainerFText, TEXT_VIRIDIANSCHOOLHOUSE_COOLTRAINER_F

ViridianSchoolHouseBrunetteGirlText:
	text_far MoveDeleterText1
	text_end

ViridianSchoolHouseCooltrainerFText:
	text_far MoveRelearnerText1
	text_end
